import streamlit as st
from cai.versioning import init_dev_version

# Initialize development version
init_dev_version()


st.set_page_config(
    page_title="CAI - Few-shot Examples Drafting Assistant",
    layout="wide",
)
st.title("Constitutional AI - Critique & Rewrite")

st.markdown("""
CAI is a tool designed to help create and refine critique+rewrite examples for Constitutional AI training, specifically focusing on the critique+rewrite step described in the [Constitutional AI paper](https://arxiv.org/pdf/2212.08073).

### What is Constitutional AI?
Constitutional AI uses reinforcement learning from AI feedback to tune models to follow a set of human-written principles--collectively referred to as the constitution. In the critique+rewrite step, a teacher model critiques and rewrites an initial completion (generated by the student model) to better adhere to a given principle from the constitution.

### Current Principle

The current implementation focuses on the following principle: **The first letter of each sentence in the assistant's response should spell "ADAPTIVE".**

### Key Features

- **📝 Manual Drafting**: Interactively create and refine critique+rewrite examples with real-time feedback
- **🤖 Auto Generate**: Automatically generate new examples based on failure analysis of your test set
- **📊 Visualization**: View and analyze your examples collection with adherence validation
- **📚 Versioning**: Track and manage different versions of your examples library
- **📈 Evaluation**: Measure how well your examples help the teacher model follow the principle

### Tool Benefits

- **Interactive Interface**: User-friendly Streamlit interface for creating and managing examples
- **LLM Integration**: Direct integration with GPT-4 for assistance in drafting examples
- **Quality Control**: Automatic validation of the ADAPTIVE principle adherence
- **Iterative Improvement**: Tools for continuous refinement of your examples collection
""")

# Initialize session state
if "human_prompt" not in st.session_state:
    st.session_state.human_prompt = ""
if "model_answer" not in st.session_state:
    st.session_state.model_answer = ""
if "critique" not in st.session_state:
    st.session_state.critique = ""
if "rewrite" not in st.session_state:
    st.session_state.rewrite = ""
if "selected_version" not in st.session_state:
    st.session_state.selected_version = "dev"
